name: CodeQL Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 1' # اجرای هفتگی هر دوشنبه ساعت 2 صبح UTC

jobs:
  analyze:
    name: Run CodeQL Analysis for eShop
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Initialize CodeQL with C# language
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'csharp'
          # queries: './.github/codeql-queries'

      # 3. Set up .NET dependencies
      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4.1.0
        with:
          global-json-file: global.json

      # 4. Install dependencies
      - name: Install dependencies
        run: dotnet restore

      # 5. Build the project (CodeQL requires a compiled project)
      - name: Build the project
        run: dotnet build --configuration Release

      # 6. Run CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          output: sarif

      # 7. Upload SARIF results to GitHub Security Tab
      - name: Upload results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeql-results.sarif
